### PR TITLE
fixes #71

### LINKED ISSUE #71: Display issues: Toast is too large, then flashes at the top during animation
### Description
The `paper-toast` element occasionally gets CSS element style `top: 0px`.

Subsequent invocations of `paper-toast`'s method `.show()` cause the toast animation to start from the top of the page.  After the animation completes, the toast displays properly at the bottom of the page.

### Expected outcome
The `paper-toast` element should by default display in the lower-left portion of the screen without expanding to the top of the screen.

The `paper-toast` element's animation behavior should not change permanently depending on when its `.show()` method is first invoked.

### Actual outcome
The `paper-toast` element fills the page top to bottom.

The `paper-toast` element animates at the top of the page before finishing at the bottom.

### Live Demo
https://jsbin.com/rudodozawa/edit?html,console,output

### Steps to reproduce
Call .show() method on `paper-toast` as Polymer is actively importing elements with `Polymer.Base.importHref()` while Page.js is changing what's displayed in `iron-pages`

### Work-around code
Add 
`this.style.position = "";`
`this.style.top = "";`
to `paper-toast`'s methods:
`.center()`
https://jsbin.com/vorufazace/1/edit?html,output

### Browsers Affected

- [x] Chrome
- [ ] Firefox // untested
- [ ] Safari 9 // reported unaffected
- [ ] Safari 8 // untested
- [ ] Safari 7 // untested
- [ ] Edge // tested unaffected
- [ ] IE 11 // untested
- [ ] IE 10 // untested

### PR DESCRIPTION
**Pull request by kf6nux**
Fixes bug discussed here: https://github.com/PolymerElements/paper-toast/issues/71

### CODE REVIEW

**Comment by kf6nux** [comment]
I signed it!

**Comment by valdrinkoshi** [comment]
Hi @kf6nux, thanks for the contribution! This needs some unit tests, so we avoid any future regression :)

**Comment by valdrinkoshi** [comment]
I would take this as an occasion to cleanup `paper-toast`, which should override `resetFit` instead of `center`, like it is done in [`iron-dropdown`](https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L421).
If you see the implementation of [`iron-fit-behavior`](https://github.com/PolymerElements/iron-fit-behavior/blob/master/iron-fit-behavior.html), `resetFit` is the right moment when to set position styles like `position/left/bottom`. It is also better to cause a relayout in there instead of `center` (because `resetFit` is called less frequently than `center`). This should also allow to remove the `_onIronResize` function from `paper-toast` https://github.com/PolymerElements/paper-toast/blob/master/paper-toast.html#L298
WDYT?

**Comment by kf6nux** [comment]
@valdrinkoshi I think that kind of cleanup is beyond the scope of what I can handle at the moment, but I trust that you're right.

I'm also not sure what's the best practice of introducing work-around code for a browser specific issue (e.g., should there be a comment on each line specifying it addresses a browser specific issue?).

All that said, I'd be happy to write some tests if we want to proceed without the cleanup.  Please let me know.  :smile:

**Comment by valdrinkoshi** [comment]
Fair, then please proceed with the unit tests, I'll open another issue for cleaning up the code ;)

**Pull request closed without merging**
