### PR TITLE
Fix safari test timeouts

### PR DESCRIPTION
**Pull request by keanulee**

### CODE REVIEW

**Comment by e111077** [comment]
🤔

**Comment by e111077** [comment]
Is there a better way to do this? Shouldn't the event listener be added before calling open?

**Comment by e111077** [comment]
seems like an iron-overlay-behavior bug

**Comment by keanulee** [comment]
Tests pass on Safari 11 on local machine, so I don't think it's an iron-overlay thing. Will try a few more things.

**Pull request merged**
