### PR TITLE
a11y friendly demo page

### LINKED ISSUE #4: paper-toast accessibility issues
Keyboard navigation issues:

-  I am unable to use just the keyboard to navigate through the buttons and activate one to trigger the toast. When I am using a screen reader, I am able to access the buttons and use the force click key command to trigger the toast, but enter does not work.

Focus:
- The animation on the buttons only appears when I use the mouse to click, not when I use the keyboard.
 
Toast Issues:
- The toasts are not being read aloud by screen readers. These need to be read as announcements
 
- In the Get Messages toast, there is the ability to click "retry". This is not keyboard accessible. If there is an action available within the toast, we need to ensure a user can get to it with the keyboard. 

- The toast times out. If a screen reader is enabled, we should consider extending the length of time it is displayed.
 
- I am unable to trigger the toast at all on Chrome OS, even when clicking the button with a mouse.
 

Windows Specific issues with NVDA:
 
- Chrome / NVDA: I can access the buttons but NVDA reads them as one: "button discard draft button get messages". This is a confusing user experience.
 
- Firefox / NVDA: there is a "blank" announced between the two buttons.

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Fixes #4 by showing toasts and allowing enough time to be read fully by readers.

### CODE REVIEW

**Comment by valdrinkoshi** [comment]
@notwaldorf WDYT?

**Comment by notwaldorf** [comment]
`iron-swipeable-container` is literally the most generic implementation. It can swipe any of its children. I don't see how a different element implementing this behaviour could be any different than the current implementation -- i.e. you can just wrap that element into this container, rather than add the behaviour to that element.

**Comment by notwaldorf** [comment]
Sorry, accidentally closed!

**Comment by notwaldorf** [comment]
LGTM

**Pull request merged**
