### PR TITLE
Spell correct 'snackbards' typo

### PR DESCRIPTION
**Pull request by dunnkers**
Fixes a small typo in the material design link.

### CODE REVIEW

**Comment by dunnkers** [comment]
I signed it!

**Comment by notwaldorf** [comment]
Heh, good catch. Thanks!

**Comment by mrherndon** [comment]
The live docs at https://elements.polymer-project.org/elements/paper-toast still have this typo in them
image

**Comment by dunnkers** [comment]
Maybe rebuild the website @notwaldorf ?

**Pull request merged**
